import org.gradle.api.tasks.compile.JavaCompile

plugins {
    id "com.android.library"
}

base {
    archivesName = "sfiora-ui"
}

android {
    namespace = "com.sandrox.sfiora.ui"
    compileSdk = 36

    defaultConfig {
        minSdk = 21
        consumerProguardFiles("consumer-rules.pro")
    }

    buildTypes {
        release {
            minifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    api project(":sfiora")
    testImplementation "junit:junit:4.13.2"
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.addAll(["-Xlint:all", "-Werror"])
}
