pluginManagement {
    def reactNativeGradlePluginPath = providers
            .gradleProperty("reactNativeGradlePluginPath")
            .get()
    includeBuild(file(reactNativeGradlePluginPath))

    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "SfioraReactNativeArtifactConsumer"
include(":app")
include(":sfiora")

def sfioraPackagePath = providers
        .gradleProperty("sfioraPackagePath")
        .get()
project(":sfiora").projectDir =
        file("${sfioraPackagePath}/android")
